name: filamentary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # Керування станом (UI реагує на бізнес-логіку)
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Локальна база даних (SQLite)
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  uuid: ^4.3.3

  # Dependency Injection (Зв'язування компонентів без жорстких залежностей)
  get_it: ^7.6.0
  injectable: ^2.3.2

  # Мережа та Логування
  dio: ^5.4.0
  logger: ^2.1.0
  http: ^1.6.0
  path_provider: ^2.1.5
  google_sign_in: ^7.2.0
  path: ^1.9.1

  # Робота з файлами, QR та друком
  qr_flutter: ^4.1.0
  pdf: ^3.10.8
  printing: ^5.11.0
  file_picker: ^8.1.4
  intl: ^0.20.2

  # ФІКС: Залишаємо тільки цей сучасний сканер. 
  # Старий qr_code_tools ПОВНІСТЮ ВИДАЛЕНО, щоб не ламати Gradle.
  mobile_scanner: ^7.2.0
  mqtt_client: ^10.11.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Генератори коду (захищають від рутини)
  drift_dev: ^2.14.1
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
